import argparse
import sys
from modules.username_search import search_username
from modules.email_analysis import check_email
from modules.phone_analysis import check_phone
from modules.image_analysis import check_image
from modules.domain_intel import check_domain
from modules.risk_scoring import calculate_risk_score
from utils.helpers import write_output_txt, write_output_json
from utils.normalizer import normalize_username, normalize_email, normalize_phone, normalize_name
from utils.validators import is_valid_username, is_valid_email, is_valid_phone, is_valid_name

def main():
    """
    InfinityTrace - Public OSINT Footprint Analyzer
    Main CLI entry point
    """
    parser = argparse.ArgumentParser(
        description="InfinityTrace - Public OSINT Footprint Analyzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python infinitytrace.py --username john_doe
  python infinitytrace.py --username john_doe --email john@example.com --json
  python infinitytrace.py --username john_doe --phone +1234567890 --output report.txt

Note: Only uses publicly available data. No identity confirmation.
        """
    )
    
    parser.add_argument("--username", type=str, help="Username to search")
    parser.add_argument("--email", type=str, help="Email to analyze (public only)")
    parser.add_argument("--phone", type=str, help="Phone to analyze (public only)")
    parser.add_argument("--name", type=str, help="Full name for soft search")
    parser.add_argument("--output", type=str, default="output.txt", help="Output filename (default: output.txt)")
    parser.add_argument("--json", action="store_true", help="Export JSON format")
    
    args = parser.parse_args()
    
    # Check if at least one input is provided
    if not any([args.username, args.email, args.phone, args.name]):
        parser.print_help()
        print("\nError: Please provide at least one input (--username, --email, --phone, or --name)")
        sys.exit(1)
    
    print("=" * 60)
    print("InfinityTrace - Public OSINT Footprint Analyzer")
    print("Generated By: Cyber Infinity")
    print("=" * 60)
    print()
    
    results = {}
    
    # Process and validate username
    if args.username:
        username = normalize_username(args.username)
        if not is_valid_username(username):
            print(f"Warning: Invalid username format: {args.username}")
            print("Username should be 3-30 characters with letters, numbers, _ or .")
        else:
            print(f"[*] Searching for username: {username}")
            results['username_input'] = username
            results['username'] = search_username(username)
            print(f"    Found {len(results['username'])} platforms")
    
    # Process and validate email
    if args.email:
        email = normalize_email(args.email)
        if not is_valid_email(email):
            print(f"Warning: Invalid email format: {args.email}")
        else:
            print(f"[*] Analyzing email: {email}")
            results['email'] = check_email(email)
            print(f"    Found {len(results['email'])} references")
    
    # Process and validate phone
    if args.phone:
        phone = normalize_phone(args.phone)
        if not is_valid_phone(phone):
            print(f"Warning: Invalid phone format: {args.phone}")
        else:
            print(f"[*] Analyzing phone: {phone}")
            results['phone'] = check_phone(phone)
            print(f"    Found {len(results['phone'])} references")
    
    # Process and validate name
    if args.name:
        name = normalize_name(args.name)
        if not is_valid_name(name):
            print(f"Warning: Invalid name format: {args.name}")
        else:
            print(f"[*] Processing name: {name}")
            results['name'] = name
    
    # Image and domain analysis (requires username)
    if args.username and results.get('username_input'):
        print(f"[*] Checking image reuse patterns")
        results['images'] = check_image(results['username_input'])
        print(f"    Generated {len(results['images'])} image check references")
        
        print(f"[*] Analyzing domain intelligence")
        results['domains'] = check_domain(results['username_input'])
        print(f"    Found {len(results['domains'])} domain-related items")
    else:
        results['images'] = []
        results['domains'] = []
    
    # Calculate overall risk
    print(f"[*] Calculating risk score...")
    risk_score, risk_level, confidence_level, risk_indicators, risk_data = calculate_risk_score(results)
    results['risk_score'] = risk_score
    results['risk_level'] = risk_level
    results['confidence_level'] = confidence_level
    results['risk_indicators'] = risk_indicators
    results['risk_data'] = risk_data
    
    print(f"    Risk Score: {risk_score}/100")
    print(f"    Risk Level: {risk_level}")
    print(f"    Confidence: {confidence_level}")
    print()
    
    # Write output
    print(f"[*] Writing output to {args.output}")
    write_output_txt(results, filename=args.output)
    print(f"    ✓ Output written to {args.output}")
    
    # Write JSON if requested
    if args.json:
        json_filename = args.output.replace('.txt', '.json') if args.output.endswith('.txt') else args.output + '.json'
        print(f"[*] Writing JSON output to {json_filename}")
        write_output_json(results, filename=json_filename)
        print(f"    ✓ JSON output written to {json_filename}")
    
    print()
    print("=" * 60)
    print("Analysis complete!")
    print("DISCLAIMER: Public data only. No identity confirmation.")
    print("=" * 60)

if __name__ == "__main__":
    main()
