"""
Write structured output to text or JSON
"""

import json
from datetime import datetime

def write_output_txt(data, filename="output.txt"):
    """
    Write a human-readable report to a text file following README format
    
    Args:
        data (dict): aggregated results from all modules
        filename (str): output file name
    """
    with open(filename, "w", encoding="utf-8") as f:
        # Header
        f.write("TARGET SUMMARY\n")
        f.write("Report Type: Public OSINT Footprint & Risk Analysis\n")
        f.write("Generated By: Cyber Infinity\n")
        f.write("Analyst Tool: InfinityTrace\n")
        f.write(f"Generated At: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} (UTC)\n")
        f.write("--------------\n")
        
        # Inputs provided
        username = data.get('username_input', 'N/A')
        f.write(f"Username        : {username}\n")
        f.write(f"Email Provided  : {'Yes' if data.get('email') else 'No'}\n")
        f.write(f"Phone Provided  : {'Yes' if data.get('phone') else 'No'}\n")
        f.write(f"Name Provided   : {'Yes' if data.get('name') else 'No'}\n")
        f.write("\n")
        
        # Platforms found
        username_results = data.get('username', [])
        if username_results:
            f.write("Platforms Found:\n")
            for platform in username_results:
                f.write(f"- {platform['platform']}: {platform['url']}\n")
            f.write("\n")
        
        # Account age and consistency (from risk data)
        risk_data = data.get('risk_data', {})
        if risk_data.get('account_age'):
            f.write(f"Account Age: {risk_data['account_age']}\n")
        if risk_data.get('profile_consistency'):
            f.write(f"Profile Consistency: {risk_data['profile_consistency']}\n")
        f.write("\n")
        
        # Risk indicators
        f.write("RISK INDICATORS\n")
        f.write("---------------\n")
        indicators = data.get('risk_indicators', [])
        if indicators:
            for indicator in indicators:
                f.write(f"• {indicator}\n")
        else:
            f.write("• No significant risk indicators detected\n")
        f.write("\n")
        
        # Email/Phone check
        f.write("EMAIL / PHONE CHECK\n")
        f.write("-------------------\n")
        email_results = data.get('email', [])
        if email_results:
            f.write(f"Email: {', '.join([r.get('source', 'Unknown') for r in email_results])}\n")
        else:
            f.write("Email: No public references found\n")
        
        phone_results = data.get('phone', [])
        if phone_results:
            f.write(f"Phone: {', '.join([r.get('source', 'Unknown') for r in phone_results])}\n")
        else:
            f.write("Phone: No public references found\n")
        f.write("\n")
        
        # Final assessment
        f.write("FINAL ASSESSMENT\n")
        f.write("----------------\n")
        f.write(f"Overall Risk Score: {data.get('risk_score', 0)} / 100\n")
        f.write(f"Risk Level: {data.get('risk_level', 'LOW')}\n")
        f.write(f"Confidence Level: {data.get('confidence_level', 'Medium')}\n")
        f.write("\n")
        
        # Disclaimer
        f.write("DISCLAIMER\n")
        f.write("----------\n")
        f.write("Public data only. No identity confirmation.\n")


def write_output_json(data, filename="output.json"):
    """
    Write machine-readable JSON output
    
    Args:
        data (dict): aggregated results from all modules
        filename (str): output file name
    """
    output = {
        "metadata": {
            "report_type": "Public OSINT Footprint & Risk Analysis",
            "generated_by": "Cyber Infinity",
            "tool": "InfinityTrace",
            "generated_at": datetime.utcnow().isoformat() + "Z",
        },
        "inputs": {
            "username": data.get('username_input'),
            "email_provided": bool(data.get('email')),
            "phone_provided": bool(data.get('phone')),
            "name_provided": bool(data.get('name'))
        },
        "results": {
            "username": data.get('username', []),
            "email": data.get('email', []),
            "phone": data.get('phone', []),
            "images": data.get('images', []),
            "domains": data.get('domains', [])
        },
        "risk_assessment": {
            "risk_score": data.get('risk_score', 0),
            "risk_level": data.get('risk_level', 'LOW'),
            "confidence_level": data.get('confidence_level', 'Medium'),
            "risk_indicators": data.get('risk_indicators', [])
        }
    }
    
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
