"""
Write structured output to text or JSON
"""

import json
from datetime import datetime, timezone, timedelta

def write_output_txt(data, filename="output.txt"):
    """
    Write human-readable output in the format specified in README
    
    Args:
        data (dict): Results dictionary containing all collected data
        filename (str): Output filename
    """
    # UTC+6 timezone (Bangladesh Standard Time)
    utc_plus_6 = timezone(timedelta(hours=6))
    timestamp = datetime.now(utc_plus_6).strftime("%Y-%m-%d %H:%M")
    
    with open(filename, "w", encoding="utf-8") as f:
        # Header
        f.write("TARGET SUMMARY\n")
        f.write("Report Type: Public OSINT Footprint & Risk Analysis\n")
        f.write("Generated By: Cyber Infinity\n")
        f.write("Analyst Tool: InfinityTrace\n")
        f.write(f"Generated At: {timestamp} (UTC+6)\n")
        f.write("--------------\n")
        
        # Input summary
        username_data = data.get('username', [])
        email_data = data.get('email', [])
        phone_data = data.get('phone', [])
        name_data = data.get('name', '')
        
        if username_data:
            # Extract username from first result or use default
            f.write(f"Username        : {data.get('username_input', 'N/A')}\n")
        
        f.write(f"Email Provided  : {'Yes' if email_data else 'No'}\n")
        f.write(f"Phone Provided  : {'Yes' if phone_data else 'No'}\n")
        f.write(f"Name Provided   : {'Yes' if name_data else 'No'}\n")
        f.write("\n")
        
        # Platforms Found
        if username_data:
            f.write("Platforms Found:\n")
            for item in username_data:
                platform = item.get('platform', 'Unknown')
                url = item.get('url', 'N/A')
                f.write(f"- {platform}: {url}\n")
            f.write("\n")
            
            # Account age and consistency (placeholder values)
            f.write("Account Age: Unknown (public data only)\n")
            profile_count = len(username_data)
            if profile_count >= 3:
                consistency = "HIGH"
            elif profile_count >= 2:
                consistency = "MEDIUM"
            else:
                consistency = "LOW"
            f.write(f"Profile Consistency: {consistency}\n")
            f.write("\n")
        
        # Risk Indicators
        f.write("RISK INDICATORS\n")
        f.write("---------------\n")
        
        risk_indicators = []
        
        if username_data and len(username_data) >= 2:
            risk_indicators.append("• Username reused on multiple platforms")
        
        image_data = data.get('images', [])
        if image_data:
            risk_indicators.append("• Public profile image analysis available")
        
        # Behavioral indicators from email/phone
        if email_data or phone_data:
            risk_indicators.append("• Email/phone found in public databases")
        
        domain_data = data.get('domains', [])
        if domain_data:
            risk_indicators.append("• Associated domains detected")
        
        if not risk_indicators:
            risk_indicators.append("• No significant risk indicators detected")
        
        for indicator in risk_indicators:
            f.write(f"{indicator}\n")
        
        f.write("\n")
        
        # Email / Phone Check
        if email_data or phone_data:
            f.write("EMAIL / PHONE CHECK\n")
            f.write("-------------------\n")
            
            if email_data:
                f.write("Email: Referenced in public datasets\n")
                for item in email_data[:3]:  # Show first 3
                    source = item.get('source', 'Unknown')
                    f.write(f"  - {source}\n")
            
            if phone_data:
                f.write("Phone: Check public spam reports\n")
                for item in phone_data[:3]:  # Show first 3
                    source = item.get('source', 'Unknown')
                    f.write(f"  - {source}\n")
            
            f.write("\n")
        
        # Final Assessment
        f.write("FINAL ASSESSMENT\n")
        f.write("----------------\n")
        
        risk_score = data.get('risk_score', 0)
        risk_level = data.get('risk_level', 'LOW')
        
        f.write(f"Overall Risk Score: {risk_score} / 100\n")
        f.write(f"Risk Level: {risk_level}\n")
        
        # Determine confidence based on amount of data
        total_findings = len(username_data) + len(email_data) + len(phone_data)
        if total_findings >= 5:
            confidence = "High"
        elif total_findings >= 2:
            confidence = "Medium"
        else:
            confidence = "Low"
        
        f.write(f"Confidence Level: {confidence}\n")
        f.write("\n")
        
        # Disclaimer
        f.write("DISCLAIMER\n")
        f.write("----------\n")
        f.write("Public data only. No identity confirmation.\n")


def write_output_json(data, filename="output.json"):
    """
    Write machine-readable JSON output
    
    Args:
        data (dict): Results dictionary containing all collected data
        filename (str): Output JSON filename
    """
    # UTC+6 timezone
    utc_plus_6 = timezone(timedelta(hours=6))
    timestamp = datetime.now(utc_plus_6).isoformat()
    
    # Calculate confidence level (same logic as TXT output)
    username_data = data.get('username', [])
    email_data = data.get('email', [])
    phone_data = data.get('phone', [])
    total_findings = len(username_data) + len(email_data) + len(phone_data)
    
    if total_findings >= 5:
        confidence = "High"
    elif total_findings >= 2:
        confidence = "Medium"
    else:
        confidence = "Low"
    
    output = {
        "metadata": {
            "report_type": "Public OSINT Footprint & Risk Analysis",
            "generated_by": "Cyber Infinity",
            "tool": "InfinityTrace",
            "timestamp": timestamp,
            "timezone": "UTC+6"
        },
        "inputs": {
            "username": data.get('username_input', None),
            "email": data.get('email_input', None),
            "phone": data.get('phone_input', None),
            "name": data.get('name', None)
        },
        "results": {
            "username_search": data.get('username', []),
            "email_analysis": data.get('email', []),
            "phone_analysis": data.get('phone', []),
            "image_analysis": data.get('images', []),
            "domain_intel": data.get('domains', [])
        },
        "assessment": {
            "risk_score": data.get('risk_score', 0),
            "risk_level": data.get('risk_level', 'LOW'),
            "confidence": confidence
        },
        "disclaimer": "Public data only. No identity confirmation."
    }
    
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
